### ISSUE TITLE
Is there a reason this needs to have VSAE to download?

### ISSUE THREAD

**Issue by Nathangau** [rafabu/SCOM-PKICertificateMP#12]
I use VSAE, but I know very few SCOM users that do and are willing to go through the effort to compile this MP to use it.

**Comment by randomnote1** [comment]
@Nathangau, on the code tab there is a link for releases. Currently it shows **2 releases**. Not the most intuitive by any means.

![image](https://user-images.githubusercontent.com/20373402/64617451-80305e80-d3ac-11e9-85b3-2077d977ddcd.png)

**Comment by rafabu** [comment]
I believe the question on VSAE has been answered by @randomnote1. So I am going to close this issue.
