### ISSUE TITLE
Is it possible to configure a report to run against a dynamic SCOM group?

### ISSUE THREAD

**Issue by RichJcoley** [rafabu/SCOM-PKICertificateMP#26]
Hi,
not an issue just a question. Forgive my ignorance as I'm fairly new to SCOM but I have a request from an end user that wishes to have the reports for expiring, expired and certificate inventory run against a dynamic group in SCOM.
If it's possible please can you tell me how I configure the reporting, which target or object should I select?
Thanks and kindest regards
Rich

**Comment by BCornelissen** [comment]
Hello Rich,
No problem.
What you do is Open the required report in SCOM reporting console.
Next at the top of the screen you see a big field for Objects. By default it will be populated with a group called All Windows Computers.
Select the Add Group... button and find the dynamic group you created. Make sure that the group you created has objects in it for either certificate stores or higher level objects (like Windows Computer!). An example is the IIS Computer Group which is part of the IIS pack. You can next remove the entry in the Objects list for the All Windows Computers.
That should give you the report as required.
Bob
