### ISSUE TITLE
Variable bIgnoreSupersededCert is undefined

### ISSUE THREAD

**Issue by dennisgmdejong** [rafabu/SCOM-PKICertificateMP#3]
The process started at 1:31:46 AM failed to create System.Discovery.Data. Errors found in output:

C:\Program Files\Microsoft System Center\Operations Manager\Server\Health Service State\Monitoring Host Temporary Files 220\6832\SystemCenterCentral.Utilities.Certificates.LocalServiceStore.Discovery.vbs(75, 1) Microsoft VBScript runtime error: Variable is undefined: 'bIgnoreSupersededCert'

**Comment by rafabu** [comment]
adding to issues list of upcoming release. doesn't seem to be anything big.

**Comment by rafabu** [comment]
Is Service Store Discovery (as opposed to LocalSystem store) still a valid scenario and if yes shouldn't this be possible by a more robust PowerShell script as well? What are your thoughts on this @BCornelissen ?

**Comment by BCornelissen** [comment]
My first thought around this is to first check if it is defined and fix that as-is. I found the line and above it this is not DIM-med. So adding it first there for the next minor version update of the pack.

**Comment by rafabu** [comment]
Fixed with v1.4.3.0
https://github.com/rafabu/SCOM-PKICertificateMP/releases/tag/v1.4.3.0
