### ISSUE TITLE
Filter for Exclude Issuer: MS-Organization- certs, does not filter out cert invalid/cert lifespan

### ISSUE THREAD

**Issue by cjramseyer** [rafabu/SCOM-PKICertificateMP#30]
The personal certificate store monitor/object discovery includes certificates used/issued by Intune + Azure AD.
These certificates are only valid for one day and do not have traditional intermediate and root certificates.

The exclusion on the discovery for the personal certificate store filters out some but not all certificates.
These certificates do not need to be monitored, and there is no exclusion overrides for cert validity (to filter certs that validity is not important) or cert lifespan, to also filter certs whose lifespan is not important.

Can this please be updated?  This MP would be great to use in our production environment, but cannot move beyond development with these issues.

**Comment by mathieudesjardins** [comment]
This is really a thing that we are facing right now. The view is populated with those kind of certificate and we would like to filter them out.
Maybe a possible override to filter out a string of text of some sort?
Would be greatly appreciated.

**Comment by cjramseyer** [comment]
This is clearly not going to have anything done for this.  It is unfortunate, but the use of this was eliminated due to this issue

**Comment by cjramseyer** [comment]
this never got any responses
