### ISSUE TITLE
I would like to install the management pack

### ISSUE THREAD

**Issue by JMvanderDuim** [rafabu/SCOM-PKICertificateMP#4]
sadly get the following message:

Cannot find resource with ID Res.TwoGroupCustomConfigurationReportDataGet_Install, Res.TwoGroupCustomConfigurationReportDataGet_Uninstall, Res.TwoGroupCustomConfigurationReportDataGet_Upgrade, Res.CustomConfigurationReport, Res.CustomGroupConfigurationReport, Res.CustomTwoGroupConfigurationReport, SCC_banner_landscape.jpg, SCC_banner_portrait.jpg, SystemCenterCentral.Utilities.Certificates.CertCRLGroup.Image16

How do I get the resource also installed.

**Comment by rafabu** [comment]
This could happen if you imported not the mpb (bundle) but individual MP files.
