### ISSUE TITLE
Certificate lifespan alert parameter replacement is not working

### ISSUE THREAD

**Issue by randomnote1** [rafabu/SCOM-PKICertificateMP#6]
The parameter replacement for the **Certificate lifespan** alert is not functioning in my environment. I am not getting errors or alerts stating that parameter replacement failed.

The following properties are null/empty:
- TemplateName
- CertVerboseTimeStatus

The following properties are not displayed in the **State Change Events** context. I assume these are not being added to the property bag.
- StoreProvider
- StoreType

**Comment by rafabu** [comment]
Fixed with v1.4.3.0
https://github.com/rafabu/SCOM-PKICertificateMP/releases/tag/v1.4.3.0
