### ISSUE TITLE
How to add this MP to SCOM 2016?

### ISSUE THREAD

**Issue by AlekseySokol** [rafabu/SCOM-PKICertificateMP#7]
I downloaded a zip file, copy to SCOM server, unzip but when I want to import MP, it's only possible to add *.mp, *.*mpb, *.xml.
But current archive doesn't contain of any mentioned above files, do I need to assemble by myself *.mp file?If yes, please provide me with a guideline how to do that.
Thank you!

**Comment by rafabu** [comment]
Have you downloaded the code as a zip file? In this case yes; you'd be expected to build your own MP using your won signing key.
However; if you just need the MP, please download the zip file linked in Releases' Assets.
[1.4.2.0-pre-release-ZIP](https://github.com/rafabu/SCOM-PKICertificateMP/releases/download/v1.4.2.0-pre-release/PKICertificateVerificationMP_1.4.2.0.zip).

**Comment by AlekseySokol** [comment]
Rafabu, thank you!
Imported successfully to SCOM.
