### ISSUE TITLE
Alert information not displayed correct in Alert Description

### ISSUE THREAD

**Issue by Fjeldsted** [rafabu/SCOM-PKICertificateMP#8]
On both "Certificate lifespan alert" and "Certificate is invalid" I don't get the expected information on the alert.  If I open Alert Context, all the info is there..

In my environment I get:
**Certificate lifespan alert**
The certificate {0}.

Certificate Subject: {1}
Certificate Issuer: {2}
Serial number: {3}

Enterpise Template: {4}
Enhanced Key Usage List: {5}

Store: {6}\{7}
Monitoring User: {8}

Chain Time Details:
{9}

**Certificate is invalid**
The certificate is not valid. Reason:
{0}

Certificate Subject: {1}
Certificate Issuer: {2}
Serial number: {3}

Enterpise Template: {4}
Enhanced Key Usage List: {5}

Store: {6}\{7}
Monitoring User: {8}

Chain Details:
{9}

**Alert Context**
Date and Time: 10-07-2019 19:40:28 
Property Name Property Value 
InstanceType Certificate 
UserContext NT AUTHORITY\SYSTEM 
CertVersion 3 
CertSerial 513E1893869EB8CF122484771B3CDB82 
CertSignatureAlgo md5RSA 
CertIssuedBy CN=Symantec Root CA, O=Symantec Corporation 
CertValidFrom 05/01/2001 00:00:00 
CertValidTo 04/30/2011 23:59:59 
CertIssuedTo CN=Symantec Root CA, O=Symantec Corporation 
CertPublicKey RSA-PKCS1-KeyEx 
CertFriendlyName  
CertThumbprint 74CDD21C2F1D104F8940DFFE7E6F035756E2F5D0 
CertSAN  
CertIsCertificateAuthority True 
CertIsSelfSigned True 
CertPrivateKey False 
CertDaysStillValid -2992 
CertLifeTimeMessage has expired on 04/30/2011 23:59:59 UTC 
CertExpiresSoon false 
CertStatus IsVerified 
CertStatusIgnoreUntrustedRoot IsVerified 
CertTimeStatus NotTimeValid: A required certificate is not within its validity period when verifying against the current system clock or the timestamp in the signed file. 
CertVerboseStatus  
CertVerboseTimeStatus --- Certificate Status --- NotTimeValid: A required certificate is not within its validity period when verifying against the current system clock or the timestamp in the signed file.  
CAVersion n/a 
TemplateName  
EnhancedKeyUsageList <null>: all purpose certificate

**Comment by shawnzzzy** [comment]
I get the same thing on mine. I'm just a beginner with management pack authoring and Github but I was thinking about taking a try and see if it's something i could fix.

**Comment by randomnote1** [comment]
This is the same as issue #6. There are two parameters in the property bag which do not appear to be populated.

**Comment by sbanyas** [comment]
We are experiencing the same issue as Fjeldsted.

randomnote1 - if two (2) parameters in the property bag are not getting populated is that "bad" enough to make none of the parameters visible?

Raphael - any ideas on this one?

**Comment by Fjeldsted** [comment]
randomnote1 - which two parameters in the property bag do not get populated?

**Comment by randomnote1** [comment]
@sbanyas, I have no idea if that'll make the difference. I attempted to modify and management pack and am awaiting testing results.

@Fjeldsted, according to my notes in issue #6, it looks like `TemplateName` and `CertVerboseTimeStatus`. It's been a while since I've looked at this issue.

**Comment by rafabu** [comment]
There is some life coming back to this as Bob has volunteered to help out on the MP maintenance. The alert parameter replacement issue(s) are high up on the list of things that should be fixed.

**Comment by BCornelissen** [comment]
RIght, In the past there were some workarounds to some fields which might be empty in the alert parameter replacement. However it looks like the Certificate Template field is now the most common culprit. We have a choice of fixing it through either passing along some content in the discovery (a "n/a" in the field if its empty), or to fix it at the alert end.
I prefer to solve it through the discovery if possible. Currently testing that with the suggestions Rafabu made.
Currently looking through other fields which might be empty, but seem to not be in the current alert parameters.

**Comment by rafabu** [comment]
Fixed with v1.4.3.0 
https://github.com/rafabu/SCOM-PKICertificateMP/releases/tag/v1.4.3.0

**Comment by Fjeldsted** [comment]
Hi

A small detail
Tag and file say v.  v1.4.3.0<https://github.com/rafabu/SCOM-PKICertificateMP/tree/v1.4.3.0>
But head line say v1.4.2.0
Think it should also say v1.4.3.0



Med venlig hilsen

Jacob Fjeldsted
Seniorkonsulent
solvo it aps

Mobil     +45 22 10 06 15
Telefon  +45 70 20 55 90

LinkedIn<http://www.linkedin.com/company/solvo-it>  ●  Facebook<https://www.facebook.com/pages/solvo-it/455011694561567>  ●  www.solvoit.com<http://www.solvoit.com/?utm_source=utm_source%3Dalm_e-mail&utm_medium=utm_medium%3Dalm_e-mail&utm_campaign=utm_campaign%3Dalm_e-mail>

[E-mailsignatur]

**Comment by rafabu** [comment]
Head line of what?

**Comment by Fjeldsted** [comment]
On https://github.com/rafabu/SCOM-PKICertificateMP/releases/tag/v1.4.3.0
[cid:image001.png@01D598AB.4B1255A0]

Med venlig hilsen

Jacob Fjeldsted
Seniorkonsulent
solvo it aps

Mobil     +45 22 10 06 15
Telefon  +45 70 20 55 90

LinkedIn<http://www.linkedin.com/company/solvo-it>  ●  Facebook<https://www.facebook.com/pages/solvo-it/455011694561567>  ●  www.solvoit.com<http://www.solvoit.com/?utm_source=utm_source%3Dalm_e-mail&utm_medium=utm_medium%3Dalm_e-mail&utm_campaign=utm_campaign%3Dalm_e-mail>

[E-mailsignatur]

**Comment by rafabu** [comment]
Thanks @Fjeldsted; spotted and changed.
Release title does now reflect the new version 1.4.3.0.
