### ISSUE TITLE
Unsupported 

### ISSUE THREAD

**Issue by hawre19h** [rafabu/SCOM-PKICertificateMP#9]
why am I getting this message when I try to import it ti VS2017 
![image](https://user-images.githubusercontent.com/53314579/61910417-3ffb4680-aefa-11e9-996c-e2fbe9cdb900.png)

**Comment by rafabu** [comment]
Have you tried installing Visual Studio Authoring Extensions (VSAE)?
https://www.microsoft.com/en-us/download/details.aspx?id=30169
However; if you just want to use the MP, a working download is available on the "Releses" tab.
